version: '3'
services:
  postgres:
    image: 'postgres:latest'
    container_name: journal
    environment:
      POSTGRES_USER: unforgettable
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: journal
    ports:
      - "5432:5432"
    restart: unless-stopped